#!/bin/bash -l
###############################################################################
#                         KM-GEN Image Classifier 
#                      Sensor Analytics Australia™ 2024
###############################################################################
# Use with YYYYMMDD-HHMMSS date stamped filenames from security cams
# For automatically generating a time-lapse over specified dates
# from saved images
NumC=10
PERC=80
FTOL=1500 # max files for time-lapse video
FR=15
## Set These Path Variables ##
PyPath=/usr/bin
PROG=/mnt/SSD/src/KM-GENe
MOVPATH=/mnt/SSD/MOVIE
DV=KM-GEN
###############################################

if [ $# -ne 3 ]; then
  echo "usage: {on|off} {YYYYMMDDHHMMSS} {YYYYMMDDHHMMSS}"
  echo "progress bar on|off start_date_time end_date_time"
  exit 1
fi

if [ ! -d $PROG ] || [ ! -d $MOVPATH ]
then
   echo "date-driver error: dir path/s do not exist!"
   exit 1
fi

echo "program ran at $(date '+%Y-%m-%d %H:%M:%S')" 

cd $PROG

MODE=$1
DT_ST=$2
DT_EN=$3

FD=$(date +%a-%H)

$PyPath/python train-km-mp.py $MODE 1 $NumC $DT_ST $DT_EN
# Keep reducing Perc threshold by 10% until under FTOL frames
# are found and Perc is still over 20%
while : ; do
  $PyPath/python predict-km.py ni $PERC 
  nf=` wc -l < ./ffnames.txt`
  [[ $nf -gt $FTOL ]] && [[ $PERC -gt 30 ]] || break
  PERC=$((PERC-10))
done

./moviefrm-list-ni $FR

mv $MOVPATH/ffnames-$DV.mp4 $MOVPATH/ffnames$DV-$FD.mp4
echo "$MOVPATH/ffnames$DV-$FD.mp4 saved"
