#!/bin/bash
# Utility to save trained kmeans model for re-use in predict-km.py
# Config.py:ImgPath must point to the images folder, with which the model was 
# trained with, when re-using saved model with predict module.

if [ $# -lt 1 ]; then
 echo "usage: {filename}"
 exit 1
fi

zip -9 $1.zip *.txt *.pkl 
unzip -lt $1.zip

if [ $? -eq 0 ]; then
 echo "trained kmeans model files saved as $1.zip"
 echo "not to be used with loadfit option"
fi
